# Generated by Django 6.0.1 on 2026-02-17 15:51

import django.db.models.deletion
import tinymce.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('todo', '0003_tag_rename_category_id_forum_category_topic'),
    ]

    operations = [
        migrations.CreateModel(
            name='Post',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False, verbose_name='id')),
                ('user', models.CharField(verbose_name='Name')),
                ('content', tinymce.models.HTMLField(default='', max_length=3000, verbose_name='Content')),
                ('created_at', models.DateTimeField(blank=True, null=True, verbose_name='Created At')),
                ('last_edited', models.DateTimeField(blank=True, null=True, verbose_name='Last Edited')),
                ('topic', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='todo.topic', verbose_name='Topic')),
            ],
            options={
                'verbose_name': 'Post',
                'verbose_name_plural': 'Posts',
            },
        ),
    ]
