# Generated by Django 6.0.1 on 2026-02-17 15:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('todo', '0004_post'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='topic',
            name='datetime',
        ),
    ]
