# Generated by Django 6.0.1 on 2026-02-18 10:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('todo', '0007_remove_topic_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tag',
            name='description',
            field=models.CharField(blank=True, null=True, verbose_name='Description'),
        ),
    ]
