# Generated by Django 6.0.1 on 2026-02-18 11:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('todo', '0009_alter_category_description_alter_forum_description'),
    ]

    operations = [
        migrations.AddField(
            model_name='forum',
            name='pinned',
            field=models.BooleanField(default=False, verbose_name='Pinned'),
        ),
    ]
