# Generated by Django 6.0.1 on 2026-02-18 11:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('todo', '0010_forum_pinned'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='forum',
            name='pinned',
        ),
        migrations.AddField(
            model_name='topic',
            name='pinned',
            field=models.BooleanField(default=False, verbose_name='Pinned'),
        ),
    ]
