# Generated by Django 6.0.1 on 2026-02-18 19:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('todo', '0011_remove_forum_pinned_topic_pinned'),
    ]

    operations = [
        migrations.AddField(
            model_name='topic',
            name='locked',
            field=models.BooleanField(default=False, verbose_name='Locked'),
        ),
    ]
