# Generated by Django 6.0.1 on 2026-02-18 19:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('todo', '0012_topic_locked'),
    ]

    operations = [
        migrations.AddField(
            model_name='category',
            name='staff_only',
            field=models.BooleanField(default=False, verbose_name='Staff Only'),
        ),
    ]
