# Generated by Django 6.0.1 on 2026-08-17 15:46

import tinymce.models
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('todo', '0016_alter_post_topic'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='flair',
            field=tinymce.models.HTMLField(default='', max_length=3000, verbose_name='Content'),
        ),
    ]
